app:
  date: ['2021-09-01', '2021-09-02', '2021-09-03']
  export_dir: "./out_of_stock/"

api:
  base_url: "https://robot-dreams-de-api.herokuapp.com"
  auth:
    endpoint: "/auth"
    payload: {"username": "rd_dreams", "password": "djT6LasE"}
    output type: "application/json"

  out_of_stock:
    endpoint: "/out_of_stock"
    output type: "application/json"